apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tridentinstallations.tridentinstall.czan.io
spec:
  group: tridentinstall.czan.io
  names:
    kind: TridentInstallation
    listKind: TridentInstallationList
    plural: tridentinstallations
    singular: tridentinstallation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
